### ISSUE TITLE
Replace Deprecated Navigator

### ISSUE THREAD

**Issue by tariq86** [tariq86/reactnative-sip#2]
The main `Navigator` component provided by `react-native` has been fully deprecated and moved from `react-native` to `react-native-deprecated-custom-components`.

To fix this, we have to add the additional package import (in `/app/containers/AppScreen.js`):
```js
import {Navigator} from 'react-native-deprecated-custom-components';
```

If this line is removed, and the module is imported from the base `react-native` library, the app will fail to load (at least when testing on my local emulator) and shows the following error:
> Navigator is deprecated and has been removed from this package. It can now be installed and imported from react-native-deprecated-custom-components instead of react-native. Learn about alternative navigation solutions at http://facebook.github.io/react-native/docs/navigation.html

Instead of continuing to use the deprecated component, we should migrate to the currently-recommended navigation component(s) [from the URL above](https://facebook.github.io/react-native/docs/navigation.html).

**Comment by targit86** [comment]
Instead of using `react-native-deprecated-custom-components`, I think it might be better to switch to  [`react-navigation`](https://reactnavigation.org/en/)

**Comment by targit86** [comment]
Closing; [see new issue here](https://github.com/tariq86/rn-sip-app/issues/5)
