### ISSUE TITLE
Dialer Button Text Cut Off

### ISSUE THREAD

**Issue by tariq86** [tariq86/reactnative-sip#4]
The letters below the digits on the keypad screen are being cut off:

![screenshot_20180501-125459_pjapp](https://user-images.githubusercontent.com/646561/39485685-279d99d0-4d3f-11e8-985d-54a41a60a3f4.jpg)

It looks like some rounded corner styling is cutting the button content off.

**Comment by targit86** [comment]
This issue has been fixed
