### ISSUE TITLE
Replace `react-native-callkit` with `react-native-callkeep`

### ISSUE THREAD

**Issue by tariq86** [tariq86/reactnative-sip#6]
As the title suggests, I think it would be better to use the [`react-native-callkeep`](https://www.npmjs.com/package/react-native-callkeep) library for two main reasons:
 1. It seems to be more actively updated
 1. It supports both iOS (via `CallKit`) and Android (via `ConnectionService`)

I'm not sure how much work it will be to make the switch, but it definitely won't be quick/easy.

**Comment by targit86** [comment]
Closing...[see issue in new repo](https://github.com/tariq86/rn-sip-app/issues/3)
